const express = require('express');
const router = express.Router();
const loanController = require('../controllers/loanController');

router.get('/eligibility/:memberId/:type', loanController.getEligibility);
router.post('/apply', loanController.applyLoan);
router.post('/fund-loan-card', loanController.fundLoanCard);
router.post('/withdraw-to-club', loanController.withdrawToClub);
router.post('/fund-from-external', loanController.fundFromExternal);
router.post('/refund-loan-fund/:txnId', loanController.refundLoanFund);
router.post('/extract-to-loan-fund', loanController.extractToLoanFund);
router.post('/extract-to-club-capital', loanController.extractToClubCapital);
router.get('/fund-status', loanController.getFundStatus);
router.get('/fund-history', loanController.getFundHistory);
router.get('/external-funders', loanController.getExternalFunders);
router.get('/', loanController.getAllLoans);
router.get('/member-loans-summary', loanController.getMemberLoansSummary);
router.get('/member-loan-statement/:memberId/pdf', loanController.memberLoanStatementPDF);
router.get('/general-loan-statement/pdf', loanController.generalLoanStatementPDF);
router.get('/repayment-schedule/:id/pdf', loanController.repaymentSchedulePDF);
router.get('/schedules-report/pdf', loanController.allSchedulesPDF);
router.get('/:id/schedule', loanController.getScheduleJSON);
router.put('/:id/status', loanController.updateLoanStatus);
router.put('/mark-paid/:loanId/:installmentNumber', loanController.markPaidByNumber);
router.put('/:id/reverse', loanController.reverseLoan);
router.delete('/:id', loanController.deleteLoan);
router.post('/check-overdue', loanController.checkOverdue);
router.get('/interest-earned', loanController.getInterestEarned);
router.get('/pending-count', loanController.getPendingCount);
router.post('/apply-late-penalty/:loanId/:installmentNumber', loanController.applyLatePenalty);
router.get('/overdue-count', loanController.getOverdueCount);
module.exports = router;